Repository kube-reporting/presto, pull requests merged in 2020-08, with the labels that each got.

#75 Dockerfile: Standardize the team mailing list across operand images.
  Dockerfile
  Dockerfile.okd
  Dockerfile.rhel
Labels: approved, lgtm

#79 Move to build script2
  Dockerfile.rhel
  opt_maven_install.sh
Labels: approved, lgtm, ok-to-test

#77 Move to conditional build_script
  Dockerfile.okd
  Dockerfile.rhel
  opt_maven_install.sh
Labels: approved

#80 Dockerfile: Add the summary label.
  Dockerfile
  Dockerfile.okd
  Dockerfile.rhel
Labels: approved, bugzilla/valid-bug, lgtm

#82 Dockerfile: Install the Python3 rpm.
  Dockerfile.rhel
Labels: approved, bugzilla/valid-bug, lgtm

#83 Bug 1872080: Alias the python command to the python3 binary.
  Dockerfile.rhel
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#84 Bug 1872080: Move the jmx prometheus jar into the correct build location.
  Dockerfile.rhel
  opt_maven_install.sh
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#89 Dockerfile: Avoid using the `alternatives` command when building outside of CI
  Dockerfile.rhel
Labels: approved, bugzilla/valid-bug, lgtm
